# Generated by Django 5.2.10 on 2026-01-22 13:51

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.JSONField()),
                ('action', models.JSONField()),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('device_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicemetric')),
            ],
            options={
                'db_table': 'rules',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.db.models.functions.datetime.Now())),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['device_metric'], name='idx_rules_device_metric'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['is_active'], name='idx_rules_is_active'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['timestamp'], name='idx_events_timestamp'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['rule'], name='idx_events_rule'),
        ),
    ]
