# Generated by Django 5.2.10 on 2026-01-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="acknowledged",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
