# Generated by Django 5.2.10 on 2026-02-03 13:24

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_event_acknowledged'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['rule', 'acknowledged'], name='idx_events_rule_ack'),
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='idx_events_rule',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='idx_events_time',
            old_name='idx_events_timestamp',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
