# Generated by Django 5.2.10 on 2026-02-08 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_event_acknowledged'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trigger_telemetry',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='triggered_events',
                to='devices.telemetry',
            ),
        ),
    ]
