# Generated by Django 5.2.10 on 2026-02-13 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_event_trigger_telemetry_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['acknowledged'], name='idx_events_ack'),
        ),
    ]
