# Generated by Django 5.2.10 on 2026-02-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_alter_event_acknowledged_alter_event_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='event',
            name='trigger_device_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the device that triggered this event', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='trigger_telemetry_id',
            field=models.BigIntegerField(blank=True, help_text='ID of the telemetry that triggered this event', null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['trigger_device_id'], name='idx_events_device_id'),
        ),
    ]
