# Generated by Django 5.2.10 on 2026-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_event_options_event_trigger_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='idx_events_telemetry_id',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='idx_events_device_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trigger_device_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trigger_telemetry_id',
        ),
        migrations.AddField(
            model_name='event',
            name='trigger_telemetry',
            field=models.JSONField(
                blank=True, help_text='Telemtry payload that triggered this event', null=True
            ),
        ),
    ]
