# Generated by Django 5.2.10 on 2026-03-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_event_options_event_trigger_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='event',
            name='idx_events_telemetry_id',
        ),
        migrations.RemoveIndex(
            model_name='event',
            name='idx_events_device_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trigger_device_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='trigger_telemetry_id',
        ),
        migrations.AddField(
            model_name='event',
            name='trigger_context',
            field=models.JSONField(blank=True, help_text='Flexible context about what triggered the event (e.g., telemetry values, thresholds)', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='trigger_device_serial_id',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.RunSQL(
            sql='ALTER TABLE events ALTER COLUMN id TYPE uuid USING (id::text::uuid);',
            reverse_sql='ALTER TABLE events ALTER COLUMN id TYPE bigint USING (id::text::bigint);'
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['trigger_device_serial_id'], name='idx_events_device_serial_id'),
        ),
    ]
