# Generated by Django 5.2.10 on 2026-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_remove_metric_check_valid_device_metric_type_and_more'),
        ('rules', '0006_remove_event_idx_events_telemetry_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rule',
            constraint=models.UniqueConstraint(
                fields=('device_metric', 'name'), name='unique_rule_name_per_device_metric'
            ),
        ),
    ]
