# Generated by Django 5.2.10 on 2026-03-07 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_event_uuid_field_and_auto_pk'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_uuid', models.UUIDField(help_text='Logical reference to the Event ID')),
                ('rule_id', models.IntegerField(help_text='Logical reference to the Rule ID')),
                ('trigger_device_serial_id', models.CharField(help_text='Device serial for quick filtering', max_length=255)),
                ('delivery_type', models.CharField(choices=[('webhook', 'Webhook'), ('notification', 'Notification')], max_length=20)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('retry', 'Retry'), ('success', 'Success'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=5)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Event Delivery',
                'verbose_name_plural': 'Event Deliveries',
                'db_table': 'event_deliveries',
                'indexes': [models.Index(fields=['status'], name='idx_event_deliveries_status'), models.Index(fields=['status', 'next_retry_at'], name='idx_event_deliv_status_retry'), models.Index(fields=['status', 'updated_at'], name='idx_event_deliv_status_updated'), models.Index(fields=['event_uuid'], name='idx_event_deliv_event_uuid'), models.Index(fields=['rule_id'], name='idx_event_deliv_rule_id'), models.Index(fields=['trigger_device_serial_id'], name='idx_event_deliv_device_id')],
                'constraints': [models.UniqueConstraint(fields=('event_uuid', 'delivery_type'), name='unique_event_delivery_type')],
            },
        ),
    ]
