# Generated by Django 5.2.10 on 2026-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_rule_unique_rule_name_per_device_metric'),
        ('rules', '0009_eventdelivery'),
    ]

    operations = [
    ]
