# Generated by Django 5.2.10 on 2026-03-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_merge_20260316_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
    ]
