# Generated by Django 5.2.10 on 2026-03-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0011_event_is_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rule',
            field=models.IntegerField(),
        ),
    ]
