# Generated by Django 5.2.10 on 2026-03-04 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('audit_event_id', models.UUIDField(help_text='Idempotency key (provided by producer)', unique=True)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('system', 'System'), ('external', 'External')], default='system', max_length=20)),
                ('actor_id', models.CharField(blank=True, max_length=100, null=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Structured metadata / payload')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='idx_audit_entity_time'), models.Index(fields=['event_type', 'occurred_at'], name='idx_audit_event_time')],
            },
        ),
    ]
