# Generated by Django 5.2.10 on 2026-01-21 12:52

from django.db import migrations
from django.contrib.postgres.operations import CreateCollation


class Migration(migrations.Migration):

    dependencies = []

    operations = [
        CreateCollation(
            "case_insensitive",
            provider="icu",
            locale="en-u-ks-level2",
            deterministic=False,
        ),
    ]
