# Generated by Django 5.2.10 on 2026-01-21 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metric_type', models.CharField(db_collation='case_insensitive', max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('numeric', 'Numeric'), ('bool', 'Boolean'), ('str', 'String')], default='numeric', max_length=10)),
            ],
            options={
                'db_table': 'metrics',
                'constraints': [models.CheckConstraint(condition=models.Q(('data_type__in', ['numeric', 'bool', 'str'])), name='check_valid_device_metric_type')],
            },
        ),
        migrations.CreateModel(
            name='DeviceMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='devices.metric')),
            ],
            options={
                'db_table': 'device_metrics',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user'], name='idx_devices_user_id'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='idx_devices_is_active'),
        ),
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['device'], name='idx_device_metrics_device'),
        ),
        migrations.AddIndex(
            model_name='devicemetric',
            index=models.Index(fields=['metric'], name='idx_device_metrics_metric'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemetric',
            unique_together={('device', 'metric')},
        ),
    ]
