# Generated by Django 5.2.10 on 2026-01-22 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("devices", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="devicemetric",
            name="device",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.device"
            ),
        ),
        migrations.AddConstraint(
            model_name="metric",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_type__in", ["numeric", "bool", "str"])),
                name="check_valid_device_metric_type",
            ),
        ),
        migrations.AddField(
            model_name="devicemetric",
            name="metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="devices.metric"
            ),
        ),
        migrations.AddField(
            model_name="telemetry",
            name="device_metric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="devices.devicemetric"
            ),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["user"], name="idx_devices_user_id"),
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(fields=["is_active"], name="idx_devices_is_active"),
        ),
        migrations.AddIndex(
            model_name="devicemetric",
            index=models.Index(fields=["device"], name="idx_device_metrics_device"),
        ),
        migrations.AddIndex(
            model_name="devicemetric",
            index=models.Index(fields=["metric"], name="idx_device_metrics_metric"),
        ),
        migrations.AlterUniqueTogether(
            name="devicemetric",
            unique_together={("device", "metric")},
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(
                fields=["device_metric", "ts"], name="idx_telemetries_metric_time"
            ),
        ),
        migrations.AddIndex(
            model_name="telemetry",
            index=models.Index(fields=["ts"], name="idx_telemetries_timestamp"),
        ),
        migrations.AddConstraint(
            model_name="telemetry",
            constraint=models.UniqueConstraint(
                fields=("device_metric", "ts"), name="unique_telemetry_per_metric_time"
            ),
        ),
    ]
