# Generated by Django 5.2.10 on 2026-02-09 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
