# Generated by Django 5.2.10 on 2026-02-10 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telemetry",
            name="ts",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
