# Generated by Django 5.2.10 on 2026-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_telemetry_ts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='metric',
            name='check_valid_device_metric_type',
        ),
        migrations.AddField(
            model_name='metric',
            name='unit',
            field=models.CharField(db_collation='case_insensitive', db_index=True, default='default', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metric',
            name='metric_type',
            field=models.CharField(db_collation='case_insensitive', db_index=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.UniqueConstraint(fields=('metric_type', 'unit'), name='unique_metric_type_with_unit'),
        ),
        migrations.AddConstraint(
            model_name='metric',
            constraint=models.CheckConstraint(condition=models.Q(('data_type__in', ['numeric', 'bool', 'str'])), name='check_valid_metric_data_type'),
        ),
    ]
